apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Cauchy-Integration-Formula
  annotations:
    github.com/project-slug: AranGarcia/Cauchy-Integration-Formula
spec:
  type: other
  lifecycle: unknown
  owner: guests
